# This is the default configuration file

# General settings
[general]
# Do not prompt if settings are not defined
prompt = false

# Package settings
[packages]
drivers-initfs = {}
init = {}
logd = {}
nulld = {}
#pciids = {}
ramfs = {}
randd = {}
redoxfs = {}
zerod = {}

[[files]]
path="/etc/init.rc"
data="""
export PATH /bin
export TMPDIR /tmp
nulld
zerod
randd
vesad T T G
logd debug: display:1
stdio log:
ps2d us
ramfs logging
acpid
pcid /etc/pcid/initfs.toml
redoxfs --uuid $REDOXFS_UUID file $REDOXFS_BLOCK
cd file:
export PATH file:/bin
run.d /etc/init.d
"""
