[source]
git = "https://gitlab.redox-os.org/redox-os/orbutils.git"

[build]
template = "custom"
script = """
COOKBOOK_CARGO_FLAGS=(
    --path "${COOKBOOK_SOURCE}"
    --root "${COOKBOOK_STAGE}/ui"
    --locked
)
cookbook_cargo
"""

[package]
dependencies = [
    "orbital"
]
