[source]
tar = "http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.6.tar.xz"
sha256 = "af00bb5a784e7c9e69f56823de4637c350643deedaf333d0fa86ecdba6fcb415"

[build]
template = "configure"
dependencies = [
    "libogg"
]
