[source]
tar = "https://codeload.github.com/xz-mirror/xz/tar.gz/v5.2.5"
script = """
./autogen.sh
"""

[build]
template = "custom"
script = """
export CFLAGS="-static"
COOKBOOK_CONFIGURE_FLAGS=(
    --host="${TARGET}"
    --prefix=""
    --disable-lzmadec
    --disable-lzmainfo
    --disable-xz
    --disable-xzdec
    --enable-shared=no
    --enable-static=yes
    --enable-threads=no
    --with-pic=no
)
cookbook_configure
"""
