[source]
tar = "https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.6.tar.bz2"

[build]
template = "custom"
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    --without-docbook
)
cookbook_configure
"""
